name: Build wheels and upload to release page

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1

      - uses: actions/upload-artifact@v3
        with:
          name: build_artifact
          path: ./wheelhouse/*.whl

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: [ build_wheels ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifact
          path: ./wheelhouse

      - name: Set up a release page
        id: setup_release
        run: |
          PYFRAME_EVAL_VERSION=$(python setup.py --version)
          tag_name="$PYFRAME_EVAL_VERSION"
          release_title="pyframe_eval $PYFRAME_EVAL_VERSION"
          echo "pyframe_eval $PYFRAME_EVAL_VERSION created at $(date)" > body.md
          echo "tag_name=${tag_name}" >> $GITHUB_OUTPUT
          echo "release_title=${release_title}" >> $GITHUB_OUTPUT

      - name: Upload tarballs
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./wheelhouse/*.whl"
          bodyFile: body.md
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.setup_release.outputs.tag_name }}"
          name: "${{ steps.setup_release.outputs.release_title }}"
          allowUpdates: true
          replacesArtifacts: true
          removeArtifacts: false

      - name: Upload tarballs
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./wheelhouse/*.whl"
          bodyFile: body.md
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "latest"
          name: "latest"
          allowUpdates: true
          replacesArtifacts: true
          removeArtifacts: false
          makeLatest: true
